services:
  main:
    build:
      context: ./image
      args:
        arch: amd64
        distro: ubuntu@sha256:bbf3d1baa208b7649d1d0264ef7d522e1dc0deeeaaf6085bf8e4618867f03494
        libc_version: '*'
    volumes:
    - $PWD:$PWD
    - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
    - DISPLAY
    - NO_AT_BRIDGE=1
    - PWNLIB_NOTERM=1
    - PYTHONIOENCODING=utf-8
    - LC_ALL=C.UTF-8
    working_dir: $PWD
    init: true
    command: sleep inf
