---
services:
  main:
    build:
      context: "./image"
      args:
        ubuntu_version: jammy
        libc_version: 2.35-0ubuntu3.1
    volumes:
      - "$PWD:$PWD"
      - "/tmp/.X11-unix:/tmp/.X11-unix"
    environment:
      - DISPLAY
      - NO_AT_BRIDGE=1
      - PWNLIB_NOTERM=1
      - PYTHONIOENCODING=utf-8
    working_dir: $PWD
    init: true
    command: sleep inf
